### ISSUE TITLE
Map shows super small

### ISSUE THREAD

**Issue by Malefic007** [Colonial-Therapist/Colonial-Therapist#16]
I changed my resolution and scale to see if it would make a difference but did not.  I also tried using the zoom on the app but it just made the white space seem larger rather than the colony part getting larger or perhaps the increase was not noticeable.  Colony is fairly mature so has all the buildings and is a decent size so not sure if maybe that  could be the issue.
![c-ther-map](https://user-images.githubusercontent.com/130177657/232238915-15481648-8d37-4f41-afcf-c2386dc520ff.png)

**Comment by skushnarev** [comment]
Thanks for the fidback!
What version of minecraft and minecolonies do you have?
Can you pass the file save/<save dir>/data/capabilities.dat, I will try to understand what is the problem.
The zoom feature is still in development, but the map shouldn't be that small.

**Comment by Malefic007** [comment]
Oh yeah version is probably the culprit .. I have been meaning to move to 1.9.2 on my next play thru but currently I have:
Minecraft Version: 1.18.2
Minecolony Version: minecolonies-1.18.2-1.0.1251-ALPHA

Also just an FYI to get the map and data to work after I selected my save folder I had to close and restart the app for the data to populate though I did not think to click refresh prior to doing that so that I am guessing pressing refresh would have probably worked.

Github would not accept .dat, so I changed the extension to .zip but it is really a .dat file not a .zip file.

[capabilities.zip](https://github.com/Colonial-Therapist/Colonial-Therapist/files/11240423/capabilities.zip)

**Comment by skushnarev** [comment]
Bug fixed in version 0.11.1
